### ISSUE TITLE
Deprecated Gradle features

### ISSUE THREAD

**Issue by LxToheedRana** [faisalcodes/bidirectional-seekbar#1]
Your work is really awesome but we cant use our lib now in latest android studio and latest gradle. 
I am facing this issue. 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Can you please resolve this issue?

**Comment by faisalcodes** [comment]
I have updated the project, kindly check.

**Comment by LxToheedRana** [comment]
I have resolved this issue almost 15 days ago sir.

**Comment by faisalcodes** [comment]
That is nice. I saw the issue today after a month. You solved the problem
by yourself it's good for you 👍.

**Comment by LxToheedRana** [comment]
❤️ ❤️
