### ISSUE TITLE
Compile error- duplicate value for resource 'attr/progress'

### ISSUE THREAD

**Issue by omkar-tenkale** [faisalcodes/bidirectional-seekbar#2]
`C:\Users\UserX\.gradle\caches\transforms-2\files-2.1\fd157b7c579f4883bb2469f4505b7355\jetified-bidirectional-seekbar-1.0.1\res\values\values.xml:3:5-60:25: AAPT: error: duplicate value for resource 'attr/progress' with config ''.`

Using as:

  ```
  <com.android.faisalkhan.seekbar.bidirectionalseekbar.BiDirectionalSeekBar
        android:id="@+id/speed"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        app:indicatorColor="@color/colorPrimary"
        app:labelColor="@color/white"
        app:maxValue="20"
        app:minValue="5"
        app:percentageSign="false"
        app:progress="10"
        app:seekBar_Style="curve"
        app:stickColor="@color/colorText"
        app:stickGap="30dp" />
```

**Comment by faisalcodes** [comment]
The problem is that the attribute "progress" is already defined somewhere in your project. To solve this issue you can remove the attribute from this library defined in values.xml.

**Comment by faisalcodes** [comment]
Hello Omkar,
The problem is that the attribute "progress" is already defined somewhere
in your project. To solve this issue you can remove the attribute from this
library defined in values.xml.

**Comment by faisalcodes** [comment]
I will fix this issue soon.

**Comment by faisalcodes** [comment]
The issue has been fixed. Now use the code like this:
<com.android.faisalkhan.seekbar.bidirectionalseekbar.BiDirectionalSeekBar
      android:id="@+id/speed"
      android:layout_width="match_parent"
      android:layout_height="60dp"
      app:BDS_indicatorColor="@color/colorPrimary"
      app:BDS_labelColor="@color/white"
      app:BDS_maxValue="20"
      app:BDS_minValue="5"
      app:BDS_percentageSign="false"
      app:BDS_progress="10"
      app:BDS_seekBar_Style="curve"
      app:BDS_stickColor="@color/colorText"
      app:BDS_stickGap="30dp" />

**Comment by faisalcodes** [comment]
The issue has been fixed. Upgrade the library and use the code like this:
```
<com.android.faisalkhan.seekbar.bidirectionalseekbar.BiDirectionalSeekBar
      android:id="@+id/speed"
      android:layout_width="match_parent"
      android:layout_height="60dp"
      app:BDS_indicatorColor="@color/colorPrimary"
      app:BDS_labelColor="@color/white"
      app:BDS_maxValue="20"
      app:BDS_minValue="5"
      app:BDS_percentageSign="false"
      app:BDS_progress="10"
      app:BDS_seekBar_Style="curve"
      app:BDS_stickColor="@color/colorText"
      app:BDS_stickGap="30dp" />
```

**Comment by omkar-tenkale** [comment]
thank you for the awesome library @faisalcodes!
